export const genres = [
  "Fiction",
  "Horror",
  "Post-Apocalyptic",
  "Dystopian",
  "Classic",
  "Science Fiction",
  "Romance",
  "Adventure",
  "Coming-of-age",
  "Fantasy",
  "Magical Realism",
  "Literary Fiction",
  "Historical Fiction",
  "Epic",
  "Epic",
  "Mythology",
  "Philosophical Fiction",
  "Gothic",
  "Philosophical Fiction",
  "Satire",
];
